### ISSUE TITLE
Data transformer unit tests sometimes fail with StackOverflowError

### ISSUE THREAD

**Issue by ionicsolutions** [anovos/anovos#169]
see e.g. https://github.com/anovos/anovos/runs/6288850865?check_suite_focus=true#step:15:2284 and https://github.com/anovos/anovos/runs/6273324296?check_suite_focus=true#step:14:3850

It seems to work fine sometimes. Not sure whether there's a pattern.

**Comment by kajanansangar** [comment]
@Vishnu-Gowthem please check whether what is causing this issue

**Comment by dattranm** [comment]
Running the isolate transformer unit test(python=3.9, spark=3.2.1, hadoop=3.2, java=11) works consistently on local. On github, it is failing occasionally as reported. 

I have tried with the same setup on github, except that it's using python=3.8 (branch [unit_test_env_order_change](https://github.com/anovos/anovos/tree/unit_test_env_order_change) and it works consistently. So my first impression is it could be something related to python 3.9 running on github environment causing StackOverflowError.

**Comment by ionicsolutions** [comment]
What change between Python 3.8 and 3.9 do you believe to be the cause for this? 

(On the branch that you linked, the tests fail for Mac OS on Python 3.7: https://github.com/anovos/anovos/runs/6356850929?check_suite_focus=true but this seems to be unrelated and due to the recent silent update of the Action. I'm in touch with the developer already.)
