### ISSUE TITLE
Issues in handling 'double' datatype

### ISSUE THREAD

**Issue by mw-vishnug** [anovos/anovos#18]
Issues while running end to end with dataset having some columns having 'double' data type.

Got error in invalidEntries_detection function
<img width="1352" alt="MicrosoftTeams-image (21)" src="https://user-images.githubusercontent.com/93873589/142202715-54c12420-aa7b-46dc-83dc-721bb0c688b5.png">

Also, some of the functions like biasedness_detection showed empty table as output
<img width="286" alt="MicrosoftTeams-image (22)" src="https://user-images.githubusercontent.com/93873589/142202743-fca93f14-61ac-48ce-8926-390e7e0cd770.png">

**Comment by nisha20verma** [comment]
IDness Detection, Biasedness Detection, and Invalid Entries Detection support only discrete columns. Hence the raised error for double type columns

**Comment by mw-vishnug** [comment]
Closing issue as changes handles as part of commit https://github.com/anovos/anovos/commit/0b56d09c1955d62996836e99e2c011c28989189f
