### ISSUE TITLE
Importing workflow from anovos in Databricks workspace results in ImportError

### ISSUE THREAD

**Issue by mathiaspet** [anovos/anovos#350]
## Expected Behavior
Import Statement completes w/o errors. 
## Current Behavior
An ImportError is thrown with the following exception: 
![image](https://user-images.githubusercontent.com/3159581/203079893-cd4deaee-458c-4cff-9feb-63ff69286b85.png)

## Steps to reproduce

1. Set up a Databricks Workspace, 
2. Open a Notebook in Python 
3. execute "%pip install anovos"
4. execute from ```anovos import workflow```
### Specifications

- Version: anovos v 1.0.1
- Platform: Databricks Workspace w/ Sparak 3.2.1
- Subsystem:

## Possible Solution
Downgrading/Fixing markupsafe library

**Comment by mathiaspet** [comment]
The error does not occur, when using the current state in main branch.

**Comment by dattranm** [comment]
Thanks @mathiaspet for reporting the issue. As per reported, this issue will be closed when we release a new version of Anovos (1.1.0)

**Comment by dattranm** [comment]
Close issue as Anovos has been updated.
