### ISSUE TITLE
confused with the following approach data_ingest read_dataset function

### ISSUE THREAD

**Issue by ziedbouf** [anovos/anovos#66]
Doing some reformating to resolve flake8 warning and for some reasons i feel like some code are very ambiguous, could someone explain the rational behind the following line of codes: 
https://github.com/anovos/anovos/blob/6020758ba68b74a0f5d61f21f184efffa57419b9/src/main/main.py#L19-L20

**Comment by kajanansangar** [comment]
@ziedbouf sorry for the delay in responding. This is to initialize the data ingestion by reading through the config file https://github.com/anovos/anovos/tree/main/config. 

I hope this clarifies your doubt.
