### ISSUE TITLE
Importing `feature_exploration` downloads almost 500MB from HuggingFace's model hub

### ISSUE THREAD

**Issue by ionicsolutions** [anovos/anovos#94]
Relevant line: https://github.com/anovos/anovos/blob/main/src/main/anovos/feature_recommender/feature_exploration.py#L6

I suggest to lazy load the model. Otherwise, simply importing the module immediately triggers a download of about 0.5 GB. That's rather surprising for users and not fair to HuggingFace.

**Comment by kajanansangar** [comment]
@dattranm here is the @ionicsolutions's suggestion https://dev.to/thibaultduponchelle/python-lazy-loading-of-an-attribute-aij

Design init_model inside each file and call it explicitly instead of implicit model loading

**Comment by dattranm** [comment]
@ionicsolutions The download only happens once when the users first setting up. After that, it will go into lazy load mode automatically, and no further download is needed once they have the model in local cache.
Though, to address the issue of designing the init_model function and call the model and data explicitly, I have created #97 about some newly created function and properly construct featrec_init. @kajanansangar you can take a look as well.

**Comment by ionicsolutions** [comment]
@dattranm Thanks for addressing the issue!

Sure, there is a cache. But every time a user imports the module for the first time, they are surprised with a >500MB download that they are not informed about and have no way of stopping. Depending on their internet connection and how their cloud provider charges for traffic, that can cause trouble.

Libraries like NLTK and spaCy hence provide separate download functionality and tell users to download the respective asset when they first invoke it. See https://www.nltk.org/data.html and https://spacy.io/usage/models for reference.

The HuggingFace model is also not lazy loaded even if it is cached: It is always loaded on import, which depending on disk speed can take some time and clutters the working memory.

**Comment by dattranm** [comment]
This issue has been resolved with #97 PR, for both adding a download function and lazy load the model.
